version: '3.8'

services:
  gitsum:
    pull_policy: always
    image: ghcr.io/colchetedao/gitsum:latest
    container_name: gitsum
    ports:
      - "3000:3000"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - /home/juanc/.ssh/gitsum/keys:/etc/gitsum/keys:ro
    
    environment:
      - GRIG_SERVER__PORT=3000
    
    restart: unless-stopped
